#pragma once

#ifndef CONFIG_H
#define CONFIG_H

#define BARE_METAL_GPIO_CONTROL_ENABLED 1
#define REGULAR_GPIO_CONTROL_ENABLED 0

#define BLUETOOTH_LOGGING_ENABLED 1
#define BLUETOOTH_TUNING_ENABLED 1

#define BRAKING_ENABLED 1
#define GAPS_ENABLED 1
#define USE_I2C_ADAPTER 1

#define LEFT_HALF_ADDRESS 0x20
#define RIGHT_HALF_ADDRESS 0x24

#define SERIAL_BAUD_RATE 115200

#define TURN_SPEED_REDUCTION_ENABLED 1

#endif