
#ifndef DEFAULTS_H
#define DEFAULTS_H

#define OUT_OF_LINE_ERROR_VALUE 20
#define LOOP_ESCAPE_ERROR_VALUE 3
#define BRAKE_DURATION_MILLIS 60
#define DEFAULT_LOOP_DELAY 9
#define DEFAULT_KP 14
#define DEFAULT_KI 0
#define DEFAULT_KD 50
#define DEFAULT_MOTOR_SPEED 90
#define WHITE_LINE_BLACK_TRACK 1
#define BLACK_LINE_WHITE_TRACK 0
#define TURN_SPEED_REDUCTION_PERCENT 15

#define STOP_DELAY 100

#endif