
#ifndef DEFAULTS_H
#define DEFAULTS_H

#define OUT_OF_LINE_ERROR_VALUE 20
#define LOOP_ESCAPE_ERROR_VALUE 3
#define BRAKE_DURATION_MILLIS 100
#define DEFAULT_LOOP_DELAY 7
#define DEFAULT_KP 12
#define DEFAULT_KI 0
#define DEFAULT_KD 70
#define DEFAULT_MOTOR_SPEED 145
#define WHITE_LINE_BLACK_TRACK 1
#define BLACK_LINE_WHITE_TRACK 0

#define STOP_DELAY 100

#endif